export const en = {
  meta: {
    title: 'Work&Walk — Every step at work counts',
    description: 'Work&Walk brings your work schedule, your steps and your pay together in one iPhone app. Free on the App Store.',
  },
  nav: { features: 'Features', devices: 'Watch & widget', pro: 'PRO', support: 'Support', download: 'Download' },
  store: { small: 'Download on the', big: 'App Store', aria: 'Download Work&Walk on the App Store' },
  hero: {
    title: ['Every step at work', 'counts.'],
    more: 'Discover the app',
    scroll: 'Scroll',
    trust: ['No account', 'No ads', 'Your data stays on your iPhone'],
    lede: 'Work&Walk brings your schedule, your steps and your pay together. Log your hours, see how much you walk during your shifts and know your net pay for the month — no spreadsheet.',
    note: 'Free · iPhone, Apple Watch and widget',
    alt: 'The Work&Walk home screen: today’s steps, hours worked and next goal',
  },
  tour: {
    eyebrow: 'The app',
    title: 'Five tabs, one working day.',
    lede: 'Tap a tab to see the screen.',
    nav: 'The app’s tabs',
    tabs: [
      {
        id: 'home', label: 'Home', title: 'Your day at a glance',
        text: 'Today’s steps, your hours worked and the next goal within reach. Below, seven days of charts that separate work from everything else.',
        points: ['Today’s steps, calories and distance', 'Work and personal side by side over 7 days', 'The milestone you are closest to'],
      },
      {
        id: 'schedule', label: 'Schedule', title: 'A schedule that fills up fast',
        text: 'Add a session in two taps, or generate the whole month from your typical schedule. Absences have their own colour and public holidays appear automatically.',
        points: ['Typical schedule: a month filled in one tap', 'Leave, sick days and public holidays', 'Year view with hours and days worked'],
      },
      {
        id: 'analysis', label: 'Analysis', title: 'Work or personal?',
        text: 'Every week, see what share of your activity comes from your shifts. Once the week is over, the recap opens into a full summary.',
        points: ['Share of your steps taken at work', 'Day-by-day detail for every metric', 'Comparison with the previous week'],
      },
      {
        id: 'salary', label: 'Salary', title: 'Your net pay, before the payslip',
        text: 'Your estimated pay is calculated from your sessions, using your own rules. You know where you stand before the month ends.',
        points: ['Tiered overtime, night and Sunday bonuses', 'Paid leave and holidays, deductible break', 'Export as PDF or CSV'],
      },
      {
        id: 'profile', label: 'Profile', title: 'Estimates that fit you',
        text: 'Your weight, height and age refine the calorie estimate. Set your step goal and follow your weight over time.',
        points: ['BMI and basal metabolic rate', 'Daily step goal', 'Weight history'],
      },
    ],
  },
  details: {
    eyebrow: 'In detail',
    title: 'The small things that save time.',
    items: [
      { icon: 'wand', title: 'AI import', text: 'Take a photo of your schedule or pick a PDF: the app turns it into sessions.', pro: true },
      { icon: 'bell', title: 'Notifications worth having', text: 'A reminder before your shift, a note at the end of the day, your recap every week. Each type has its own switch.' },
      { icon: 'calendar', title: 'Automatic public holidays', text: 'French public holidays appear in your schedule, for every year, with nothing to enter.' },
      { icon: 'lock', title: 'Salary behind Face ID', text: 'Lock the Salary tab: it only opens with your face or your passcode.' },
      { icon: 'globe', title: 'French and English', text: 'Choose the app’s language and your currency, independently of the phone’s settings.' },
      { icon: 'map', title: 'A guided tour', text: 'On first launch, the app shows you every screen with sample data, then starts from scratch.' },
    ],
    theme: { title: 'Light or dark', text: 'The app follows the phone’s theme, or the one you prefer.', alt: 'The home screen in the light theme, compared with the dark theme', dark: 'Dark', light: 'Light', slider: 'Compare the light and dark themes' },
  },
  devices: {
    eyebrow: 'On your wrist and your home screen',
    title: 'Your numbers, without opening the app.',
    watch: { title: 'Apple Watch', text: 'Your steps, hours, pay for the day, your shift times and your next goal. A complication shows your steps on the watch face.', alt: 'The Work&Walk app on Apple Watch' },
    widget: { title: 'Widget', text: 'Your steps, hours, calories and pay for the day on the home screen. It updates by itself throughout the day.', alt: 'The Work&Walk widget: 2,154 steps, 21% of 10,000, 8 hours of work, 86 kcal and €95 of pay', ui: { steps: 'steps', goal: '21% of 10k', work: 'Work', calories: 'Calories', pay: 'Pay' } },
  },
  goals: {
    eyebrow: 'Goals',
    title: '42 milestones to reach, one shift at a time.',
    lede: 'Your progress moves with every finished session. When a shift takes you past a milestone, you get a notification as you leave work.',
    alt: 'The goals screen with six categories',
    items: [
      { label: 'Steps', name: 'Great Walker', value: 0.61, color: '#ff9500' },
      { label: 'Attendance', name: 'Employee Model', value: 0.52, color: '#ff6666' },
      { label: 'Work time', name: 'Relentless', value: 0.86, color: '#ffbf00' },
      { label: 'Fortune', name: 'Nest Egg', value: 0.79, color: '#cc6600' },
      { label: 'Consistency', name: 'On a Roll', value: 0.75, color: '#ed5c0a' },
      { label: 'Step record', name: 'Ten Thousand', value: 0.8, color: '#d99a1a' },
    ],
  },
  pro: {
    eyebrow: 'Work&Walk PRO',
    title: 'The app is free. PRO goes further.',
    lede: 'The schedule, step tracking and pay estimate are free. The PRO subscription adds what follows, and can be managed at any time from the app’s settings.',
    items: [
      { title: 'Automatic AI import', text: 'Your schedule as a photo or PDF becomes sessions.' },
      { title: 'Unlimited history', text: 'Go back as far as you like, instead of two weeks.' },
      { title: 'Export your record', text: 'Your pay estimate as a PDF and the month’s detail as CSV.' },
      { title: 'Advanced health', text: 'Distance, heart rate and flights, at work and outside it.' },
      { title: 'A helping hand', text: 'You directly support the app’s development.' },
    ],
  },
  privacy: {
    eyebrow: 'Privacy',
    title: 'Your data stays on your iPhone.',
    points: [
      'Your sessions, pay and profile are saved on your device. No account to create.',
      'Your health data never leaves your devices.',
      'No advertising, no tracking tools.',
    ],
    note: 'One exception, and only if you use it: AI import sends the document you choose so its hours can be read.',
    link: 'Read the privacy policy',
  },
  cta: { title: 'Start with your first session.', lede: 'Free on the App Store. A one-minute guided tour, then it’s over to you.' },
  footer: { updated: 'Website updated on', cookies: 'Cookies', reset: 'Clear my preferences', resetDone: 'Preferences cleared.', print: 'Print', nav: 'Useful links', tagline: 'Every step at work counts.', privacy: 'Privacy', support: 'Support', contact: 'Contact', rights: 'All rights reserved.', apple: 'Apple, iPhone, Apple Watch and App Store are trademarks of Apple Inc.' },
  support: {
    title: 'Support',
    lede: 'Answers to the most common questions.',
    contactTitle: 'Another question?',
    contactText: 'Write to us and we’ll get back to you as soon as possible.',
    contactCta: 'Send an email',
    print: 'Print this page',
    faq: [
      { q: 'Is the app free?', a: 'Yes. The schedule, step tracking and pay estimate are free. The optional PRO subscription adds AI import, unlimited history, PDF and CSV export and advanced health metrics.' },
      { q: 'How do I add a work session?', a: 'Open the Schedule tab and tap the + button. Choose the start and end, add your break if you have one, then save. To fill a whole month, turn on the typical schedule in settings: a button then appears in the schedule to generate the sessions.' },
      { q: 'How is my pay calculated?', a: 'From your sessions, your hourly rate and your deduction percentage. You can add tiered overtime, night and Sunday bonuses, paid leave and public holidays, and deduct the break. Everything is set from the Salary tab. The result is an estimate, not a payslip.' },
      { q: 'I can’t see my steps — what should I do?', a: 'Check that Work&Walk has access to Health: iPhone Settings > Health > Data Access & Devices > Work&Walk. Then reopen the app: figures refresh every time you return.' },
      { q: 'Is my data stored in the cloud?', a: 'No. Your sessions, pay and profile stay on your iPhone, and your health data never leaves your devices. Only AI import sends the document you choose, to extract its hours.' },
      { q: 'How do I log leave or a sick day?', a: 'In Schedule, tap the umbrella icon, then +. Choose the type and the dates. French public holidays appear automatically; you can turn them off in settings.' },
      { q: 'How do I change plan or manage my subscription?', a: 'In the app, open settings (the gear on the home screen), then the Subscription section. You can switch between monthly and annual there, or open your App Store subscription management.' },
      { q: 'I have an offer code — where do I enter it?', a: 'Open the subscription screen and tap “I have a code” at the bottom. You can also use the link you received directly.' },
      { q: 'Does the app work with Apple Watch?', a: 'Yes. The Apple Watch app shows your steps, hours, pay for the day and next goal, and a complication can show your steps on the watch face.' },
      { q: 'How do I replay the guided tour?', a: 'In settings, under Help, tap “Replay the guided tour”. It uses sample data and does not change yours.' },
    ],
  },
  policy: {
    title: 'Privacy policy',
    updated: 'Last updated: 7 October 2026',
    sections: [
      { title: '1. Health data', text: 'With your permission, Work&Walk reads from Apple Health (HealthKit) your step count, distance travelled, active calories, heart rate and flights climbed. This data is used only to display your statistics in the app, its widget and its Apple Watch app.\nIf you turn on the “Save as workout” option, the app also writes your work sessions to Apple Health as walking workouts.\nYour health data never leaves your devices and is not used for advertising or profiling.' },
      { title: '2. Data stored on your device', text: 'Your work sessions, absences, pay estimates, profile and settings are saved locally on your device. Work&Walk requires no account and holds no copy of this data.' },
      { title: '3. AI schedule import', text: 'When you use the schedule import, the image or PDF you choose is sent to our server and then to OpenAI’s artificial intelligence service, solely to extract your working hours. Our server does not store this document; OpenAI may retain it temporarily under its own terms of use.\nA proof of purchase signed by Apple is sent with the request to verify your subscription. No health data or any other app data is transmitted.\nDo not import a document containing information you do not wish to share.' },
      { title: '4. Subscription', text: 'Purchases and subscriptions are handled by Apple. Work&Walk does not receive your name, your email address or your payment details.' },
      { title: '5. Notifications', text: 'Notifications are scheduled locally on your device based on your schedule. No server is used to send them.' },
      { title: '6. Data sharing', text: 'We do not sell, trade or transfer any of your personal data for commercial purposes. The app contains no advertising and no tracking tools.' },
      { title: '7. This website', text: 'This website sets no advertising cookies and uses no third-party analytics. It remembers, in your browser, the language you chose and your answer to the cookie banner.\nLinks to the App Store indicate that they come from this website. If you accept, the website also keeps, for the duration of your visit, the campaign parameters (UTM) of the link that brought you here and adds them to the App Store link, in order to know where downloads come from. None of this information can identify you.\nYou can change your choice at any time with the “Cookies” link at the bottom of the page, or erase everything with “Clear my preferences”.' },
      { title: '8. Your rights', text: 'You can withdraw access to your health data at any time in Settings > Health > Data Access & Devices > Work&Walk. You can erase all app data from Settings > Reset data, or by deleting the app.' },
      { title: '9. Contact', text: 'For any question about this policy, write to us at workandwalkapp@gmail.com.' },
    ],
  },
  a11y: { skip: 'Skip to content', menu: 'Open menu', close: 'Close', top: 'Back to top', language: 'Language', progress: 'Reading progress', loading: 'Loading…', home: 'Work&Walk, home', main: 'Main navigation' },
  faq: { eyebrow: 'Frequently asked', title: 'What people ask us most.', more: 'All questions' },
  cookies: {
    title: 'Cookies and measurement',
    text: 'No advertising cookies here. If you accept, the website remembers, for the duration of your visit, the link that brought you here, so we know what gets the app discovered.',
    more: 'Learn more',
    accept: 'Accept',
    decline: 'Decline',
  },
  contact: { button: 'Contact us', title: 'A question?', text: 'Write to us, we reply as soon as we can.', email: 'Write an email', copy: 'Copy the address', copied: 'Address copied', faq: 'Browse the help page' },
  confirm: {
    resetTitle: 'Clear your preferences?',
    resetText: 'The language you chose and your answer to the cookie banner will be removed from this browser. The website will go back to its original settings.',
    resetOk: 'Clear',
    cancel: 'Cancel',
  },
  notFound: { title: 'Page not found', back: 'Back to home' },
}
