export const fr = {
  meta: {
    title: 'Work&Walk — Chaque pas au travail compte',
    description: 'Work&Walk réunit ton planning, tes pas et ton salaire dans une seule app iPhone. Gratuit sur l’App Store.',
  },
  nav: { features: 'Fonctionnalités', devices: 'Montre et widget', pro: 'PRO', support: 'Aide', download: 'Télécharger' },
  store: { small: 'Télécharger dans', big: 'l’App Store', aria: 'Télécharger Work&Walk dans l’App Store' },
  hero: {
    title: ['Chaque pas au travail', 'compte.'],
    more: 'Découvrir l’app',
    scroll: 'Fais défiler',
    trust: ['Sans compte', 'Sans publicité', 'Tes données restent sur ton iPhone'],
    lede: 'Work&Walk réunit ton planning, tes pas et ton salaire. Note tes heures, vois combien tu marches pendant tes postes et connais ton net du mois, sans tableur.',
    note: 'Gratuit · iPhone, Apple Watch et widget',
    alt: 'L’écran d’accueil de Work&Walk : pas du jour, heures travaillées et prochain objectif',
  },
  tour: {
    eyebrow: 'L’app',
    title: 'Cinq onglets, une journée de travail.',
    lede: 'Touche un onglet pour voir l’écran.',
    nav: 'Les onglets de l’app',
    tabs: [
      {
        id: 'home', label: 'Accueil', title: 'Ta journée en un coup d’œil',
        text: 'Tes pas du jour, tes heures travaillées et le prochain objectif à ta portée. En dessous, sept jours de graphiques qui séparent le travail du reste.',
        points: ['Pas, calories et distance du jour', 'Travail et perso côte à côte sur 7 jours', 'Le palier dont tu es le plus proche'],
      },
      {
        id: 'schedule', label: 'Planning', title: 'Un planning qui se remplit vite',
        text: 'Ajoute une session en deux gestes, ou génère tout le mois depuis ton horaire type. Les absences ont leur couleur et les jours fériés s’affichent tout seuls.',
        points: ['Horaire type : un mois rempli en un appui', 'Congés, maladie et jours fériés', 'Vue année avec heures et jours travaillés'],
      },
      {
        id: 'analysis', label: 'Analyse', title: 'Travail ou perso ?',
        text: 'Chaque semaine, vois quelle part de ton activité vient de tes postes. Une fois la semaine terminée, le récap s’ouvre en bilan complet.',
        points: ['Part de tes pas faits au travail', 'Détail jour par jour pour chaque mesure', 'Comparaison avec la semaine précédente'],
      },
      {
        id: 'salary', label: 'Salaire', title: 'Ton net, sans attendre la fiche de paie',
        text: 'Ton salaire estimé se calcule à partir de tes sessions, avec tes propres règles. Tu sais où tu en es avant la fin du mois.',
        points: ['Heures sup par tranches, nuit et dimanche', 'Congés et jours fériés payés, pause déductible', 'Export en PDF ou en CSV'],
      },
      {
        id: 'profile', label: 'Profil', title: 'Des estimations à ta mesure',
        text: 'Ton poids, ta taille et ton âge affinent le calcul de tes calories. Fixe ton objectif de pas et suis l’évolution de ton poids.',
        points: ['IMC et métabolisme de base', 'Objectif de pas quotidien', 'Historique du poids'],
      },
    ],
  },
  details: {
    eyebrow: 'Dans le détail',
    title: 'Les petites choses qui font gagner du temps.',
    items: [
      { icon: 'wand', title: 'Import par IA', text: 'Prends ton planning en photo ou choisis un PDF : l’app en tire toutes tes sessions.', pro: true },
      { icon: 'bell', title: 'Des notifications utiles', text: 'Un rappel avant ton poste, un mot en fin de journée, ton récap chaque semaine. Chaque type se règle séparément.' },
      { icon: 'calendar', title: 'Jours fériés automatiques', text: 'Les jours fériés français apparaissent dans ton planning, pour toutes les années, sans rien saisir.' },
      { icon: 'lock', title: 'Salaire sous Face ID', text: 'Verrouille l’onglet Salaire : il ne s’ouvre qu’avec ton visage ou ton code.' },
      { icon: 'globe', title: 'Français et anglais', text: 'Choisis la langue de l’app et ta devise, indépendamment des réglages du téléphone.' },
      { icon: 'map', title: 'Une visite guidée', text: 'Au premier lancement, l’app te montre chaque écran avec des données d’exemple, puis repart de zéro.' },
    ],
    theme: { title: 'Clair ou sombre', text: 'L’app suit le thème du téléphone, ou celui que tu préfères.', alt: 'L’écran d’accueil en thème clair, comparé au thème sombre', dark: 'Sombre', light: 'Clair', slider: 'Comparer le thème clair et le thème sombre' },
  },
  devices: {
    eyebrow: 'Au poignet et sur l’écran d’accueil',
    title: 'Tes chiffres, sans ouvrir l’app.',
    watch: { title: 'Apple Watch', text: 'Tes pas, tes heures, ton salaire du jour, les horaires de ton poste et ton prochain objectif. Une complication affiche tes pas sur le cadran.', alt: 'L’app Work&Walk sur Apple Watch' },
    widget: { title: 'Widget', text: 'Tes pas, tes heures, tes calories et ton salaire du jour sur l’écran d’accueil. Il se met à jour tout seul au fil de la journée.', alt: 'Le widget Work&Walk : 2 154 pas, soit 21 % de 10 000, 8 heures de travail, 86 kcal et 95 € de salaire', ui: { steps: 'pas', goal: '21% de 10k', work: 'Travail', calories: 'Calories', pay: 'Salaire' } },
  },
  goals: {
    eyebrow: 'Objectifs',
    title: '42 paliers à franchir, un poste après l’autre.',
    lede: 'Ta progression avance à chaque session terminée. Quand un poste te fait franchir un palier, tu reçois une notification en sortant du travail.',
    alt: 'L’écran des objectifs avec six catégories',
    items: [
      { label: 'Pas', name: 'Grand Marcheur', value: 0.61, color: '#ff9500' },
      { label: 'Assiduité', name: 'Salarié Modèle', value: 0.52, color: '#ff6666' },
      { label: 'Temps de travail', name: 'Acharné', value: 0.86, color: '#ffbf00' },
      { label: 'Fortune', name: 'Bas de Laine', value: 0.79, color: '#cc6600' },
      { label: 'Régularité', name: 'Sur la Lancée', value: 0.75, color: '#ed5c0a' },
      { label: 'Record de pas', name: 'Dix Mille', value: 0.8, color: '#d99a1a' },
    ],
  },
  pro: {
    eyebrow: 'Work&Walk PRO',
    title: 'L’app est gratuite. PRO va plus loin.',
    lede: 'Le planning, le suivi des pas et l’estimation du salaire sont gratuits. L’abonnement PRO ajoute ce qui suit, et se gère à tout moment depuis les réglages de l’app.',
    items: [
      { title: 'Import automatique par IA', text: 'Ton planning en photo ou en PDF devient des sessions.' },
      { title: 'Historique illimité', text: 'Remonte aussi loin que tu veux, au lieu de deux semaines.' },
      { title: 'Export de ta fiche', text: 'Ta fiche estimative en PDF et le détail du mois en CSV.' },
      { title: 'Santé avancée', text: 'Distance, cardio et étages, au travail et en dehors.' },
      { title: 'Un coup de pouce', text: 'Tu soutiens directement le développement de l’app.' },
    ],
  },
  privacy: {
    eyebrow: 'Confidentialité',
    title: 'Tes données restent sur ton iPhone.',
    points: [
      'Tes sessions, ton salaire et ton profil sont enregistrés sur ton appareil. Pas de compte à créer.',
      'Tes données de santé ne quittent jamais tes appareils.',
      'Ni publicité, ni outil de suivi.',
    ],
    note: 'Une seule exception, et seulement si tu t’en sers : l’import par IA envoie le document que tu choisis pour en lire les horaires.',
    link: 'Lire la politique de confidentialité',
  },
  cta: { title: 'Commence par ta première session.', lede: 'Gratuit sur l’App Store. Une minute de visite guidée, puis c’est à toi.' },
  footer: { updated: 'Site mis à jour le', cookies: 'Cookies', reset: 'Effacer mes préférences', resetDone: 'Préférences effacées.', print: 'Imprimer', nav: 'Liens utiles', tagline: 'Chaque pas au travail compte.', privacy: 'Confidentialité', support: 'Aide', contact: 'Contact', rights: 'Tous droits réservés.', apple: 'Apple, iPhone, Apple Watch et App Store sont des marques d’Apple Inc.' },
  support: {
    title: 'Aide',
    lede: 'Les réponses aux questions les plus fréquentes.',
    contactTitle: 'Une autre question ?',
    contactText: 'Écris-nous, on te répond dès que possible.',
    contactCta: 'Envoyer un e-mail',
    print: 'Imprimer cette page',
    faq: [
      { q: 'L’app est-elle gratuite ?', a: 'Oui. Le planning, le suivi des pas et l’estimation du salaire sont gratuits. L’abonnement PRO, optionnel, ajoute l’import par IA, l’historique illimité, l’export PDF et CSV et les mesures de santé avancées.' },
      { q: 'Comment ajouter une session de travail ?', a: 'Ouvre l’onglet Planning et touche le bouton +. Choisis le début et la fin, ajoute ta pause si tu en as une, puis enregistre. Pour remplir un mois entier, active l’horaire type dans les réglages : un bouton apparaît alors dans le planning pour générer les sessions.' },
      { q: 'Comment mon salaire est-il calculé ?', a: 'À partir de tes sessions, de ton taux horaire et de ton pourcentage de charges. Tu peux y ajouter des heures supplémentaires par tranches, des majorations de nuit et du dimanche, des congés et jours fériés payés, et déduire la pause. Tout se règle depuis l’onglet Salaire. Le résultat est une estimation, pas une fiche de paie.' },
      { q: 'Je ne vois pas mes pas, que faire ?', a: 'Vérifie que Work&Walk a accès à Santé : Réglages de l’iPhone > Santé > Accès aux données et appareils > Work&Walk. Puis rouvre l’app : les chiffres se mettent à jour à chaque retour.' },
      { q: 'Mes données sont-elles stockées dans le cloud ?', a: 'Non. Tes sessions, ton salaire et ton profil restent sur ton iPhone, et tes données de santé ne quittent jamais tes appareils. Seul l’import par IA envoie le document que tu choisis, pour en extraire les horaires.' },
      { q: 'Comment noter un congé ou un arrêt maladie ?', a: 'Dans le Planning, touche l’icône parasol, puis +. Choisis le type et les dates. Les jours fériés français s’affichent automatiquement ; tu peux les désactiver dans les réglages.' },
      { q: 'Comment changer de formule ou gérer mon abonnement ?', a: 'Dans l’app, ouvre les réglages (l’engrenage sur l’accueil), puis la section Abonnement. Tu peux y passer du mensuel à l’annuel, ou ouvrir la gestion de ton abonnement App Store.' },
      { q: 'J’ai un code d’offre, où le saisir ?', a: 'Ouvre l’écran d’abonnement et touche « J’ai un code » en bas. Tu peux aussi utiliser directement le lien que tu as reçu.' },
      { q: 'L’app fonctionne-t-elle avec l’Apple Watch ?', a: 'Oui. L’app Apple Watch affiche tes pas, tes heures, ton salaire du jour et ton prochain objectif, et une complication peut afficher tes pas sur le cadran.' },
      { q: 'Comment revoir la visite guidée ?', a: 'Dans les réglages, section Aide, touche « Revoir la visite guidée ». Elle utilise des données d’exemple et ne modifie pas les tiennes.' },
    ],
  },
  policy: {
    title: 'Politique de confidentialité',
    updated: 'Dernière mise à jour : 7 octobre 2026',
    sections: [
      { title: '1. Données de santé', text: 'Avec votre accord, Work&Walk lit dans Apple Santé (HealthKit) votre nombre de pas, votre distance parcourue, vos calories actives, votre fréquence cardiaque et vos étages montés. Ces données servent uniquement à afficher vos statistiques dans l’application, son widget et son app Apple Watch.\nSi vous activez l’option « Enregistrer comme workout », l’application écrit aussi vos sessions de travail dans Apple Santé sous forme de séances de marche.\nVos données de santé ne quittent jamais vos appareils et ne sont utilisées ni pour de la publicité ni pour du profilage.' },
      { title: '2. Données stockées sur votre appareil', text: 'Vos sessions de travail, vos absences, vos estimations de salaire, votre profil et vos réglages sont enregistrés localement sur votre appareil. Work&Walk ne demande aucun compte et ne possède aucune copie de ces données.' },
      { title: '3. Import de planning par IA', text: 'Lorsque vous utilisez l’import de planning, l’image ou le PDF que vous choisissez est envoyé à notre serveur, puis au service d’intelligence artificielle d’OpenAI, dans le seul but d’en extraire vos horaires. Notre serveur n’enregistre pas ce document ; OpenAI peut le conserver temporairement selon ses propres conditions d’utilisation.\nUne preuve d’achat signée par Apple accompagne la requête afin de vérifier votre abonnement. Aucune donnée de santé ni aucune autre donnée de l’application n’est transmise.\nN’importez pas de document contenant des informations que vous ne souhaitez pas partager.' },
      { title: '4. Abonnement', text: 'Les achats et les abonnements sont gérés par Apple. Work&Walk ne reçoit ni votre nom, ni votre adresse e-mail, ni vos moyens de paiement.' },
      { title: '5. Notifications', text: 'Les notifications sont programmées localement sur votre appareil à partir de votre planning. Aucun serveur n’est utilisé pour les envoyer.' },
      { title: '6. Partage des données', text: 'Nous ne vendons, n’échangeons et ne transférons aucune de vos données personnelles à des fins commerciales. L’application ne contient ni publicité ni outil de suivi.' },
      { title: '7. Ce site', text: 'Ce site ne dépose aucun cookie publicitaire et n’utilise aucun outil de mesure d’audience tiers. Il mémorise dans votre navigateur la langue que vous avez choisie et votre réponse au bandeau cookies.\nLes liens vers l’App Store indiquent qu’ils proviennent de ce site. Si vous l’acceptez, le site conserve aussi, le temps de votre visite, les paramètres de campagne (UTM) du lien par lequel vous êtes arrivé et les ajoute au lien vers l’App Store, afin de savoir d’où viennent les téléchargements. Aucune de ces informations ne permet de vous identifier.\nVous pouvez modifier votre choix à tout moment avec le lien « Cookies » en bas de page, ou tout effacer avec « Effacer mes préférences ».' },
      { title: '8. Vos droits', text: 'Vous pouvez retirer l’accès à vos données de santé à tout moment dans Réglages > Santé > Accès aux données et appareils > Work&Walk. Vous pouvez effacer toutes les données de l’application depuis Paramètres > Réinitialiser les données, ou en supprimant l’application.' },
      { title: '9. Contact', text: 'Pour toute question concernant cette politique, écrivez-nous à workandwalkapp@gmail.com.' },
    ],
  },
  a11y: { skip: 'Aller au contenu', menu: 'Ouvrir le menu', close: 'Fermer', top: 'Retour en haut de page', language: 'Langue', progress: 'Progression dans la page', loading: 'Chargement…', home: 'Work&Walk, accueil', main: 'Navigation principale' },
  faq: { eyebrow: 'Questions fréquentes', title: 'Ce qu’on nous demande le plus.', more: 'Toutes les questions' },
  cookies: {
    title: 'Cookies et mesure',
    text: 'Aucun cookie publicitaire ici. Si tu l’acceptes, le site retient, le temps de ta visite, le lien par lequel tu es arrivé, pour savoir ce qui fait connaître l’app.',
    more: 'En savoir plus',
    accept: 'Accepter',
    decline: 'Refuser',
  },
  contact: { button: 'Nous contacter', title: 'Une question ?', text: 'Écris-nous, on te répond dès que possible.', email: 'Écrire un e-mail', copy: 'Copier l’adresse', copied: 'Adresse copiée', faq: 'Consulter l’aide' },
  confirm: {
    resetTitle: 'Effacer tes préférences ?',
    resetText: 'La langue choisie et ta réponse au bandeau cookies seront supprimées de ce navigateur. Le site reviendra à ses réglages d’origine.',
    resetOk: 'Effacer',
    cancel: 'Annuler',
  },
  notFound: { title: 'Page introuvable', back: 'Retour à l’accueil' },
}
